---
- name: INSTALL NCCL
  block:
    - name: Install NCCL from CUDA repository for RHEL
      yum:
        name:
          - "libnccl-{{ nccl_package_version }}"
          - "libnccl-devel-{{ nccl_package_version }}"
          - "libnccl-static-{{ nccl_package_version }}"
        state: latest
      environment: "{{proxy_env if proxy_env is defined else {}}}"
      when:
        - ansible_os_family == 'RedHat'

    - name: Install NCCL from CUDA repository for Ubuntu
      apt:
        name:
           - "libnccl2={{ nccl_package_version }}"
           - "libnccl-dev={{ nccl_package_version }}"
        state: present
      environment: "{{proxy_env if proxy_env is defined else {}}}"
      when:
        - ansible_distribution == 'Ubuntu'
  rescue:
    - name: Install NCCL from CUDA repository for RHEL
      yum:
        name:
          - "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/tlS7lj6rssynVCjVlw0Wjdh9MR4unczgxGJKdMLOTgFjaMBTWh70CZRty4O088jm/n/hpc/b/source/o/nccl/libnccl-{{ nccl_package_version }}.el7.x86_64.rpm"
          - "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/tlS7lj6rssynVCjVlw0Wjdh9MR4unczgxGJKdMLOTgFjaMBTWh70CZRty4O088jm/n/hpc/b/source/o/nccl/libnccl-devel-{{ nccl_package_version }}.el7.x86_64.rpm"
          - "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/tlS7lj6rssynVCjVlw0Wjdh9MR4unczgxGJKdMLOTgFjaMBTWh70CZRty4O088jm/n/hpc/b/source/o/nccl/libnccl-static-{{ nccl_package_version }}.el7.x86_64.rpm"
        state: latest
        disable_gpg_check: true
      environment: "{{proxy_env if proxy_env is defined else {}}}"
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '7'

    - name: Install NCCL from CUDA repository for RHEL
      yum:
        name:
          - "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/tlS7lj6rssynVCjVlw0Wjdh9MR4unczgxGJKdMLOTgFjaMBTWh70CZRty4O088jm/n/hpc/b/source/o/nccl/libnccl-{{ nccl_package_version }}.el8.x86_64.rpm"
          - "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/tlS7lj6rssynVCjVlw0Wjdh9MR4unczgxGJKdMLOTgFjaMBTWh70CZRty4O088jm/n/hpc/b/source/o/nccl/libnccl-devel-{{ nccl_package_version }}.el8.x86_64.rpm"
          - "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/tlS7lj6rssynVCjVlw0Wjdh9MR4unczgxGJKdMLOTgFjaMBTWh70CZRty4O088jm/n/hpc/b/source/o/nccl/libnccl-static-{{ nccl_package_version }}.el8.x86_64.rpm"
        state: latest
        disable_gpg_check: true
      environment: "{{proxy_env if proxy_env is defined else {}}}"
      when:
        - ansible_os_family == 'RedHat'
        - ansible_distribution_major_version == '8'

    - name: Install NCCL from Oracle Build repo
      become: true
      apt:
        deb: "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/tlS7lj6rssynVCjVlw0Wjdh9MR4unczgxGJKdMLOTgFjaMBTWh70CZRty4O088jm/n/hpc/b/source/o/nccl/libnccl2_{{ nccl_package_version }}_amd64.deb"
      when:
        - ansible_distribution == 'Ubuntu'

    - name: Install NCCL from Oracle Build repo
      become: true
      apt:
        deb: "https://objectstorage.eu-frankfurt-1.oraclecloud.com/p/tlS7lj6rssynVCjVlw0Wjdh9MR4unczgxGJKdMLOTgFjaMBTWh70CZRty4O088jm/n/hpc/b/source/o/nccl/libnccl-dev_{{ nccl_package_version }}_amd64.deb"
      when:
        - ansible_distribution == 'Ubuntu'
